### ISSUE TITLE
open a new tab next to the current , Should be for all but not one 

### ISSUE THREAD

**Issue by ghost** [gilmoreorless/chrome-new-tab-here#1]

**Comment by gilmoreorless** [comment]
To clarify, do you mean that it should (optionally) force all new tabs to open next to the current one? Unfortunately Chrome doesn't allow the default New Tab behaviour to be overridden by extensions, so this is the best I can get at the moment.

**Comment by lyscop** [comment]
Oh, it is a nice thought, and it is a pity that it can not be achieved.
